version: "3.8"

services:
  backend:
    image: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}:${BACKEND_TAG}"
    container_name: "itsoftlab_backend_${ENVIRONMENT}_${COLOR}"
    env_file:
      - backend/.env
    ports:
      - "${HOST_BACKEND_PORT}:5300"
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "512M"
    # networks:
    #   - hrms_network

  frontend:
    image: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}:${FRONTEND_TAG}"
    container_name: "itsoftlab_frontend_${ENVIRONMENT}_${COLOR}"
    env_file:
      - frontend/.env
    ports:
      - "${HOST_FRONTEND_PORT}:3300"
    stdin_open: true
    tty: true
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "512M"  
